// skills_generated.js — AUTO-GENERATED by OpenClaw
//
// This file contains dynamically generated skill definitions.
// OpenClaw watches evolution/triggers/ and edits this file to add new skills
// as the colony advances technologically.
//
// Manual edits are allowed but may be overwritten by OpenClaw.
// To add permanent skills, add them to skills.js instead.

export const GENERATED_SKILLS = [
  // OpenClaw will add new skill definitions here as the colony evolves.
  // Example format:
  // { id: 'smelting', name: 'Smelting', category: 'Crafting', era: 'metallurgy',
  //   description: 'Turning rocks into slightly more useful rocks, but hot.',
  //   effects: [{ type: 'taskOutput', task: 'Smelt', stat: 'metal', rate: 0.06 }],
  //   graph: 'metal-output' },
];
