// tasks_generated.js — AUTO-GENERATED by OpenClaw
//
// This file contains dynamically generated task definitions.
// OpenClaw watches evolution/triggers/ and edits this file to add new tasks
// as the colony advances technologically.
//
// Manual edits are allowed but may be overwritten by OpenClaw.
// To add permanent tasks, add them to main.js instead.
//
// Task format (data-driven):
// { id: 'Smelt', name: 'Smelt Ore', era: 'metallurgy',
//   enabled: (s) => !!s.unlocked.metallurgy,
//   inputs: [{ res: 'ore', rate: 0.5 }, { res: 'wood', rate: 0.3 }],
//   outputs: [{ res: 'metal', rate: 0.8 }],
//   energy: 0.04, hunger: 0.035,
//   skills: ['smelting', 'fire-tending', 'endurance'],
//   xpRates: [0.35, 0.15, 0.10] }

export const GENERATED_TASKS = [
  // OpenClaw will add new task definitions here.
];
